# Generated by Django 2.2.28 on 2023-08-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vwcss'),
    ]

    operations = [
        migrations.CreateModel(
            name='XZAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdkd', models.BigIntegerField()),
                ('ewtretye', models.BigIntegerField()),
            ],
        ),
    ]
